[package]
name = "next-online-judge-backend"
authors = ["AprilNEA <github@sku.moe>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
# safety
bcrypt = "0.15.0"
# web framework
## server
actix-web = "4"
actix-cors = "0.6.4"
actix-identity = "0.6.0"
actix-session = { version = "0.8.0", features = ["redis-actor-session"] }
## client
reqwest = { version = "0.11", features = ["json"] }
## tools
url = "2.2"
chrono = { version = "0.4.31", features = ["serde"] } # time
# serde
serde = "1.0.188"
serde_json = "1.0.107"
# sql
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres", "json"] }
log = "0.4.20"
futures = "0.3.28"


