[package]
name = "next-online-judge-backend"
authors = ["AprilNEA <github@sku.moe>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
# web framework
## server
actix-web = "4"
actix-cors = "0.6.4"
## client
reqwest = { version = "0.11", features = ["json"] }
## tools
url = "2.2"
# serde
serde_json = "1.0.107"
# sql
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "postgres", "json"] }

