[package]
name = "next-online-judge-backend"
authors = ["AprilNEA <github@sku.moe>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
rand = "0.8.5"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.28"
# safety
bcrypt = "0.15.0"
# web framework
## server
actix-web = "4"
actix-cors = "0.6.4"
actix-identity = "0.6.0"
actix-session = { version = "0.8.0", features = ["redis-actor-session"] }
## client
reqwest = { version = "0.11", features = ["json"] }
## tools
url = "2.2"
chrono = { version = "0.4.31", features = ["serde"] } # time
# serde
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
# redis
redis = { version = "0.23.3", features = ["tokio-comp"] }
# sql
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres", "json", "chrono"] }
# task queue
apalis = { version = "0.4", features = ["redis"] }
fang = { version = "0.10.4" , features = ["asynk"], default-features = false }
bb8 = "0.8.1"
bb8-redis = "0.13.1"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
